### ISSUE TITLE
Reference to env variables loaded from .env before dotenv configuration

### ISSUE THREAD

**Issue by antoinegag** [NerdEli/Custom-Discord-Bot#1]
Hi, was just looking at the code of the bot and I noticed that you reference 
`process.env.TWITCH_KEY; ` 
https://github.com/NerdEli/Custom-Discord-Bot/blob/1bad1c1d774e52f984b261890905d4c88fb1ceb5/bot.js#L20

_before_ calling `require("dotenv").config(); `
https://github.com/NerdEli/Custom-Discord-Bot/blob/1bad1c1d774e52f984b261890905d4c88fb1ceb5/bot.js#L52

This causes the `CLIENT_ID` to be undefined since the env variables haven't been loaded.

The dotenv [usage doc](https://www.npmjs.com/package/dotenv#usage) says that you should call it _as early as possible_ in your application, I'd suggest moving it to the top completely.

**Comment by NerdEli** [comment]
Fixed as of [dd7e2db](https://github.com/NerdEli/Custom-Discord-Bot/commit/dd7e2dbd3d52d740cedd0dd7e28fc964880f37af)
